spring:
 profiles:
   active: dev
   group:
     dev: dev, common, secret-dev
     minjae: minjae-server, common, secret-prod
     jinhyun: jinhyun-server, common, secret-prod
     qorrbs: qorrbs-server, common, secret-prod
     hyeondeok: hyeondeok-server, common, secret-prod
---

spring:
  config:
    activate:
      on-profile: dev

cors:
  allow-origin: "http://localhost:5173"
---

spring:
  config:
    activate:
      on-profile: minjae-server

cors:
  allow-origin:
    - "https://"
---

spring:
  config:
    activate:
      on-profile: jinhyun-server

cors:
  allow-origin:
    - "https://allwaysfreshmarket.store"
---

spring:
  config:
    activate:
      on-profile: qorrbs-server

cors:
  allow-origin:
    - "https://allwayyys/store"
---

spring:
  config:
    activate:
      on-profile: hyeondeok-server

cors:
  allow-origin:
    - "https://nationalallwayspj.store"
---
spring:
  config:
    activate:
      on-profile: common

springdoc:
  swagger-ui:
    path: doc

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.korit.allways_back.entity

logging:
  level:
    com.korit.allways_back.mapper: debug

server:
  servlet:
    session:
      cookie:
        same-site: lax
        http-only: true

