spring:
 profiles:
   active: dev
   group:
     dev: dev, common, secret-dev
     minjae: minjae-server, common, secret-prod
     jinhyun: jinhyun-server, common, secret-prod

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: minjae-server

---

spring:
  config:
    activate:
      on-profile: jinhyun-server
      
---
spring:
  config:
    activate:
      on-profile: common # 'local'이 활성화될 때 이 아래 설정을 읽으라고 명시!

springdoc:
  swagger-ui:
    path: doc

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.korit.allways_back.entity

logging:
  level:
    com.korit.allways_back.mapper: debug

server:
  servlet:
    session:
      cookie:
        same-site: lax
        http-only: true
